### ISSUE TITLE
Singular matrix error for large datasets

### ISSUE THREAD

**Issue by amitesh863** [kelvnt/data-drift-detector#4]
Error log

-> 170            kde_prior = gaussian_kde(col_prior)

/opt/conda/lib/python3.7/site-packages/scipy/stats/kde.py in __init__(self, dataset, bw_method, weights)
    204             self._neff = 1/sum(self._weights**2)
    205 
--> 206         self.set_bandwidth(bw_method=bw_method)
    207 
    208     def evaluate(self, points):

/opt/conda/lib/python3.7/site-packages/scipy/stats/kde.py in set_bandwidth(self, bw_method)
    552             raise ValueError(msg)
    553 
--> 554         self._compute_covariance()
    555 
    556     def _compute_covariance(self):

/opt/conda/lib/python3.7/site-packages/scipy/stats/kde.py in _compute_covariance(self)
    564                                                bias=False,
    565                                                aweights=self.weights))
--> 566             self._data_inv_cov = linalg.inv(self._data_covariance)
    567 
    568         self.covariance = self._data_covariance * self.factor**2

/opt/conda/lib/python3.7/site-packages/scipy/linalg/basic.py in inv(a, overwrite_a, check_finite)
    966         inv_a, info = getri(lu, piv, lwork=lwork, overwrite_lu=1)
    967     if info > 0:
--> 968         raise LinAlgError("singular matrix")
    969     if info < 0:
    970         raise ValueError('illegal value in %d-th argument of internal '

Error
LinAlgError: singular matrix

Getting singular matrix error while working with large datasets frequently. Can computation of coraiance method be done using a different method instead of linalg.inverse?

**Comment by amitesh863** [comment]
One possible solution:

The issue is caused by some columns and drift calculation can still be done on other columns. A try except block to filter out the columns that cause this issue should solve it 

```
for col in numeric_columns:
    # fit gaussian_kde
    exception_list = []
    try: 
        col_prior = X_train_split[col].dropna()
        col_post = X_test_split[col].dropna()
        kde_prior = gaussian_kde(col_prior)
        kde_post = gaussian_kde(col_post)
    except:
        exception_list.append(col)
```

**Comment by kelvnt** [comment]
I suspect your issue is likely due to many repeated numbers in the column of your large dataframe - look at this thread here: https://stats.stackexchange.com/questions/89754/statsmodels-error-in-kde-on-a-list-of-repeated-values

As this pertains to scipy's `gaussian_kde` implementation, I will not be making any changes to the data drift detector. Such issues should be highlighted and reflected to the user and thus I'm against using a try and except block to skirt around the problem. You may simply specify the numeric columns (and exclude the one that's causing you errors) that you wish to calculate drift for in the `numeric_columns` argument when you initialize the detector.

**Comment by amitesh863** [comment]
Yeah, that's why I had added the exception list which could be returned to the user to indicate that these columns are problematic. But the drift computation for other variables should not be hindered because of this as the computation is being done on individual columns. Thanks for replying!
